# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-20 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailerId', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('masterCode', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('quantity', models.FloatField()),
                ('imageurl', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('retailerId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('adress', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='contain',
            name='masterCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
