# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-20 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contain',
            old_name='masterCode',
            new_name='productId',
        ),
        migrations.RenameField(
            model_name='contain',
            old_name='retailerId',
            new_name='storeId',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='retailerId',
            new_name='storeId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default='N/A', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contain',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='masterCode',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='adress',
            field=models.CharField(max_length=300),
        ),
    ]
