# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-20 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200220_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='masterCode',
            new_name='productId',
        ),
    ]
