# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-20 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200220_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contain',
            name='price',
            field=models.FloatField(),
        ),
    ]
