# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-20 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200220_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contain',
            old_name='storeId',
            new_name='storeId_id',
        ),
    ]
