# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-20 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200220_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='storeId',
            new_name='id',
        ),
    ]
