# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-26 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200220_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contain',
            name='productId',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='Contain',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
