# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-26 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0007_auto_20200526_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('rank', models.IntegerField()),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('engName', models.CharField(default='N/A', max_length=200)),
                ('vieName', models.CharField(default='N/A', max_length=200)),
                ('bard', models.CharField(default='N/A', max_length=50)),
                ('size', models.CharField(default='N/A', max_length=50)),
                ('price', models.IntegerField()),
                ('exp', models.CharField(max_length=20)),
                ('uses', models.CharField(max_length=1000)),
                ('manuals', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=50)),
                ('urlInfo', models.CharField(max_length=50)),
                ('publish', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=1000)),
            ],
        ),
    ]
