# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-26 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rank',
            new_name='seri',
        ),
    ]
